services:

  # ==========================================================
  # Apache
  # ==========================================================

  apache:
    build:
      context: ./apache
    container_name: multidomain-apache

    ports:
      - "80:80"

    volumes:
      - ./src/php/sites:/var/www/sites:ro
      - ./src/php/shared:/var/www/shared:ro

    depends_on:
      - php-main
      - php-admin

    networks:
      - web


  # ==========================================================
  # Main localhost site
  # ==========================================================

  php-main:
    image: php:8.5-fpm
    container_name: multidomain-php-main

    volumes:
      - ./src/php/sites/main:/var/www/sites/main:ro
      - ./src/php/shared:/var/www/shared:ro
      - ./php/main/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

    cpus: "0.50"
    mem_limit: 512m

    networks:
      - web


  # ==========================================================
  # app1.localhost
  # ==========================================================

  php-admin:
    image: php:8.5-fpm
    container_name: multidomain-php-admin

    volumes:
      - ./src/php/sites/admin:/var/www/sites/admin:ro
      - ./src/php/shared:/var/www/shared:ro
      - ./php/admin/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro

    cpus: "0.50"
    mem_limit: 512m

    networks:
      - web


networks:
  web: