# ============================================================
# localhost
# ============================================================

<VirtualHost *:80>

    ServerName localhost

    DocumentRoot "/var/www/sites/main"

    <Directory "/var/www/sites/main">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    DirectoryIndex index.php index.html

    # Send PHP files to PHP-FPM
    <FilesMatch "\.php$">
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined

</VirtualHost>


# ============================================================
# Dynamic subdomains
# ============================================================

<VirtualHost *:80>

    ServerName example.localhost
    ServerAlias *.localhost

    # %1 = first part of hostname
    #
    # app1.localhost -> /var/www/sites/app1
    # app2.localhost -> /var/www/sites/app2
    # shop.localhost -> /var/www/sites/shop

    VirtualDocumentRoot "/var/www/sites/%1"

    <Directory "/var/www/sites">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    DirectoryIndex index.php index.html

    # Send PHP files to PHP-FPM
    <FilesMatch "\.php$">
        SetHandler "proxy:fcgi://php:9000"
    </FilesMatch>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined

</VirtualHost>